services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=listit
      - POSTGRES_PASSWORD=devpassword
      - POSTGRES_DB=listit
    ports:
      - "5432:5432" # exposes Portgres to your machine for sqlx CLI
    volumes:
      - postgres_data:/var/lib/postgresql/data


  app:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://listit:devpassword@db:5432/listit
      - JWT_SECRET=change-me
      - RUST_LOG=debug
      - PORT=3000
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates

volumes:
  postgres_data:
  
